[project]
name = "amarillo-gtfs-generator"
version = "2.0.0"
description = "FastAPI app providing GTFS generation for Amarillo carpools"
readme = "README.md"
license = {file = "LICENSE"}
dependencies = [
    "amarillo",
    "schedule",
    "watchdog",
]

[tool.setuptools.packages]
find = {}
